package com.drartisan.entity;
// Generated 2015-11-12 18:53:48 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Img generated by hbm2java
 */
@Entity
@Table(name = "img", catalog = "drartisan")
public class Img implements java.io.Serializable {

	private Integer id;
	private Integer subgoodid;
	private String url;

	public Img() {
	}

	public Img(Integer subgoodid, String url) {
		this.subgoodid = subgoodid;
		this.url = url;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "subgoodid")
	public Integer getSubgoodid() {
		return this.subgoodid;
	}

	public void setSubgoodid(Integer subgoodid) {
		this.subgoodid = subgoodid;
	}

	@Column(name = "url", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
