package com.drartisan.entity;
// Generated 2015-11-12 18:53:48 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subgood generated by hbm2java
 */
@Entity
@Table(name = "subgood", catalog = "drartisan")
public class Subgood implements java.io.Serializable {

	private Integer id;
	private Integer goodsid;
	private String name;
	private String headimg;
	private Double oprice;
	private Double price;
	private String link;

	public Subgood() {
	}

	public Subgood(Integer goodsid, String name, String headimg, Double oprice, Double price, String link) {
		this.goodsid = goodsid;
		this.name = name;
		this.headimg = headimg;
		this.oprice = oprice;
		this.price = price;
		this.link = link;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "goodsid")
	public Integer getGoodsid() {
		return this.goodsid;
	}

	public void setGoodsid(Integer goodsid) {
		this.goodsid = goodsid;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "headimg", length = 200)
	public String getHeadimg() {
		return this.headimg;
	}

	public void setHeadimg(String headimg) {
		this.headimg = headimg;
	}

	@Column(name = "oprice", precision = 22, scale = 0)
	public Double getOprice() {
		return this.oprice;
	}

	public void setOprice(Double oprice) {
		this.oprice = oprice;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Column(name = "link", length = 300)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

}
